<a href="https://colab.research.google.com/github/anshikaaggarwalmca2025-sys/PythonPrograms-Data-Visualization-/blob/main/employee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
df = pd.read_excel("https://github.com/anshikaaggarwalmca2025-sys/PythonPrograms-Data-Visualization-/raw/refs/heads/main/employee_dataset_5000_records.xlsx")
df.head(10)

,Employee_ID,Name,Department,Email,Salary,Join_Date
0,E3331,Kavita Mishra,IT,kavita.mishra@company.com,119001.0,2023-04-16
1,E1054,Neha Gupta,HR,neha.gupta@company.com,96408.0,2015-07-16
2,E3518,Sneha Kapoor,IT,sneha.kapoor@company.com,27678.0,2019-12-16
3,E5090,Priya Singh,Operations,priya.singh@company.com,52603.0,2015-12-09
4,E2202,Priya Singh,Operations,priya.singh@company.com,110177.0,2023-03-24
5,E4322,Rohit Agarwal,Sales,rohit.agarwal@company.com,53857.0,2020-12-09
6,E3482,Neha Gupta,Finance,neha.gupta@company.com,61529.0,2021-01-26
7,E1859,Rohit Agarwal,Sales,rohit.agarwal@company.com,98330.0,2015-02-06
8,E4948,Sneha Kapoor,Finance,sneha.kapoor@company.com,60752.0,2022-05-30
9,E1662,Rahul Verma,Sales,rahul.verma@company.com,73548.0,2017-11-30

In [11]:
df.tail()

,Employee_ID,Name,Department,Email,Salary,Join_Date
4995,E5105,Rohit Agarwal,Finance,rohit.agarwal@company.com,84003.0,2021-08-21
4996,E3863,Riya Das,Operations,riya.das@company.com,59880.0,2023-03-15
4997,E4828,Rohit Agarwal,Sales,rohit.agarwal@company.com,114478.0,NaN
4998,E4204,Kavita Mishra,HR,kavita.mishra@company.com,113683.0,2023-06-20
4999,E1374,Ankit Jain,Marketing,ankit.jain@company.com,64044.0,2018-06-09